ref_vel_configulator:
  s0_start_straight:
    ref_vel: 45.0
    wp_id: 1
  s1_corner1:
    ref_vel: 40.0
    wp_id: 60
  s2_straight1:
    ref_vel: 45.0
    wp_id: 85
  s3_hairpin1:
    ref_vel: 38.0
    wp_id: 110
  s4_straight2:
    ref_vel: 45.0
    wp_id: 135
  s5_corner2:
    ref_vel: 39.0
    wp_id: 160
  s6_straight3:
    ref_vel: 45.0
    wp_id: 190
  s7_corner3:
    ref_vel: 39.0
    wp_id: 210
  s8_chicane_early_brake:
    ref_vel: 37.0
    wp_id: 225
  s9_chicane_hairpin:
    ref_vel: 37.0
    wp_id: 240
  s10_chicane_exit_curve:
    ref_vel: 38.0
    wp_id: 260
  s11_straight4:
    ref_vel: 45.0
    wp_id: 300
  s12_corner4:
    ref_vel: 39.0
    wp_id: 305
  s13_corner5:
    ref_vel: 39.0
    wp_id: 325
  s14_final_straight:
    ref_vel: 45.0
    wp_id: 340
