#!/usr/bin/env python3

import sys
import cProfile

# ROS 2
import rclpy
from rclpy.signals import SignalHandlerOptions

# Project
from multi_purpose_mpc_ros_with_dynamic_param.mpc_controller import MPCController
from multi_purpose_mpc_ros_with_dynamic_param.mpc_simulation import MPCSimulation
from multi_purpose_mpc_ros_with_dynamic_param.common import parse_args_without_ros


def main(argv = sys.argv) -> None:

    args = parse_args_without_ros(argv)
    rclpy.init(args=argv)
    try:
        node = MPCController(args.config_path)
        sim = MPCSimulation(node)
        sim.run()
    except KeyboardInterrupt:
        node.get_logger().info("Shutdown requested")
    finally:
        node.destroy_node()


if __name__ == "__main__":
    main(sys.argv)
