#!/usr/bin/env python3

import sys

# ROS 2
import rclpy
from rclpy.signals import SignalHandlerOptions

# Project
from multi_purpose_mpc_ros_with_dynamic_param.tools.reference_path_visualizer import ReferencePathVisualizer
from multi_purpose_mpc_ros_with_dynamic_param.common import parse_args_without_ros


def main(argv = sys.argv) -> None:

    args = parse_args_without_ros(argv)
    rclpy.init(args=argv, signal_handler_options=SignalHandlerOptions.NO)

    node = ReferencePathVisualizer(args.config_path)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        rclpy.shutdown()


if __name__ == "__main__":
    main(sys.argv)
